---
sidebar: sidebar 
permalink: configuration-analysis.html 
keywords: evs, well-architected, configuration analysis, best practices, recommendations 
summary: Workload Factory가 Amazon Elastic VMware Service 구성을 분석하여 문제를 식별하고 모범 사례 권장 사항을 제공하는 방법을 알아보세요. 
---
= EVS 구성에 대한 구성 분석
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Workload Factory는 Amazon Elastic VMware Service(EVS) 구성을 정기적으로 분석하여 모범 사례와의 불일치를 파악합니다. 분석 결과를 활용하여 성능, 비용 효율성 및 규정 준수를 개선하십시오.

주요 기능은 다음과 같습니다:

* 일일 구성 분석
* 자동 모범 사례 검증
* 사전 예방적 관찰 가능성
* 인사이트를 실행으로




== 작동 방식

Workload Factory는 Amazon FSx for NetApp ONTAP 파일 시스템 배포 환경에서 실행되는 워크로드를 매일 분석합니다. 이 분석을 통해 아키텍처 상태, 인사이트 및 권장 사항을 확인할 수 있습니다.

일일 분석이 완료되면 배포의 Well-architected 대시보드에 구성 상태가 "최적화됨" 또는 "최적화되지 않음"으로 표시됩니다. 총 최적화 점수, 범주별 구성 문제, 구성 문제 및 권장 사항 목록을 확인할 수 있습니다. 구성 문제에 대한 권장 사항을 검토할 수 있습니다. 일부 문제는 Workload Factory에서 자동으로 수정되지만, 다른 문제는 수동 개입이 필요합니다. 이 경우 Workload Factory는 권장 변경 사항을 구현하는 데 도움이 되는 자세한 지침을 제공합니다.

사용 환경에 적용되지 않는 구성에 대한 분석은 제외할 수 있습니다. 이렇게 하면 불필요한 경고와 부정확한 최적화 결과를 방지할 수 있습니다. 특정 구성 분석을 제외하면 Workload Factory는 해당 구성을 전체 최적화 점수 계산에 포함하지 않습니다.



== 중요한 이유

Workload Factory는 지속적인 평가와 권장 사항 인사이트 및 문제 해결을 결합하여 대규모 스토리지, 데이터베이스 및 VMware 환경에 모범 사례를 적용합니다. Workload Factory 콘솔에서 적용되는 자동화된 수정 사항은 인적 오류를 줄이고 일관된 관리를 보장하며 워크로드 인프라 전반의 성능과 안정성을 유지합니다.



== 분석 요구 사항

완벽한 구성 분석을 위해서는 다음을 수행해야 합니다.

* 링크를 연결하세요. 링크 연결을 통해 Workload Factory는 데이터 보호 및 성능과 같은 모든 파일 시스템 구성을 분석할 수 있습니다.
+
link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["기존 링크를 연결하는 방법 또는 새 링크를 생성하고 연결하는 방법을 알아보십시오"].

* VMware 워크로드에 대한 _보기, 계획 및 분석_ 권한을 부여합니다.
+
link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["AWS 계정에 권한을 부여하는 방법을 알아보십시오"^]

* AWS 계정에 최소 하나 이상의 검색된 Amazon Elastic VMware Service 환경이 있어야 합니다.




== EVS 워크로드에 대한 모범 사례 및 권장 사항

Workload Factory는 잘 설계된 Amazon Elastic VMware Service(EVS) 워크로드 운영을 위한 모범 사례 및 권장 사항을 제공합니다. 잘 설계된 분석은 EVS 구성을 평가하여 VMware 환경이 안정성, 보안, 운영 우수성, 비용 최적화 및 성능 효율성 측면에서 최적화되도록 지원합니다. VMware의 잘 설계된 상태 탭에서 EVS 환경에 대한 잘 설계된 모범 사례를 구현하는 데 도움이 되는 인사이트와 권장 사항을 확인할 수 있습니다.

잘 설계된 분석은 프레임워크의 다음 핵심 요소인 _신뢰성_ 및 _보안_을 기준으로 구성을 분류합니다.



=== 안정성

안정성은 중단이 발생하더라도 워크로드가 의도된 기능을 정확하고 일관되게 수행하도록 보장합니다.

* *EVS 환경 복원력*
+
EVS 클러스터 노드가 파티션 배치 그룹에 올바르게 분산되어 있는지 확인하십시오. 모든 노드는 4개 이상의 파티션으로 구성된 단일 파티션 배치 그룹의 구성원이어야 합니다. 올바른 파티션 배치는 AWS 가용 영역 내의 여러 장애 격리 하드웨어 파티션에 EVS 클러스터 노드가 분산되도록 보장합니다. 잘못 배치되면 파티션 장애 발생 시 처리 능력 손실이나 다운타임이 크게 발생할 수 있습니다.





=== 보안

보안은 위험 평가 및 완화 전략을 통해 데이터, 시스템 및 자산을 보호하는 데 중점을 둡니다.

* *클러스터 노드 관리*
+
EVS 클러스터 노드에 적절한 EC2 중지 및 종료 보호 기능이 구성되어 있는지 확인하십시오. EVS ESXi 노드는 vCenter 또는 기타 VMware 수준의 관리 도구를 사용하여 관리해야 합니다. 적절한 EC2 수준 보호 기능이 없으면 EC2 콘솔에서 노드가 실수로 중지되거나 종료될 수 있으며, 이로 인해 가상 머신 데이터의 사용 불가 또는 데이터 손실이 발생할 수 있습니다.



.다음 단계
link:view-evs-well-architected.html["잘 설계된 구성 구현"]
