---
sidebar: sidebar 
permalink: launch-migration-advisor-evs-manual.html 
keywords: overview, concepts, features, use case, workloads, how workload factory works, migration, advisor, manual, specification, deploy, deployment, plan 
summary: NetApp 워크로드 팩토리에 로그인하여 VMware 마이그레이션 조언자에 액세스합니다. 마법사의 단계를 따라 필요에 맞게 사용자 지정된 배포 계획 또는 마이그레이션 계획을 만듭니다. 
---
= VMware 워크로드 마이그레이션 어드바이저를 사용하여 Amazon EVS에 대한 배포 계획을 만듭니다.
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp 워크로드 팩토리에 로그인하여 VMware 마이그레이션 조언자에 액세스합니다. 마법사의 단계를 따라 필요에 맞게 사용자 지정된 배포 계획 또는 마이그레이션 계획을 만듭니다.

워크로드 팩토리얼에 액세스하려면 사용자 이름과 암호가 있어야 합니다. 액세스 권한이 없는 경우 지금 계정을 만드십시오. 자세한 내용은 지침을 https://docs.netapp.com/us-en/workload-setup-admin/quick-start.html["여기"]참조하십시오.



== 환경 요구 사항을 수동으로 지정하여 배포 계획을 만듭니다.

Amazon Elastic VMware Service의 가상 머신에 대한 요구 사항을 수동으로 지정하고 사용자 정의된 Amazon FSx for NetApp ONTAP 파일 시스템을 외부 데이터 저장소로 사용할 수 있습니다.

.요구 사항
* Amazon Elastic VMware Service 구독이 있어야 합니다.


.단계
. 중 하나를 사용하여 워크로드 팩토리에 https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["콘솔 환경"^] 로그인합니다.
. 선택적으로 Workload Factory 콘솔에서 Workload Factory에 액세스한 경우 VMware 워크로드 타일에서 *계획 및 생성*을 선택한 다음 *Amazon Elastic VMware 서비스*를 선택합니다. VMware Migration Advisor 시작 화면이 표시됩니다.
. *Amazon Elastic VMware 서비스* 타일을 선택합니다.
. 준비가 되면 * 시작 * 을 선택합니다.
. VM 환경에 대한 요구 사항을 입력하세요.
+
[NOTE]
====
다음 VM 마이그레이션 성능 요구 사항과 권장 사항을 염두에 두세요.

** 성능상의 이유로 VM 인벤토리에는 최소 10TiB의 저장 용량이 권장됩니다.
** 이 배포에 대해 지정한 필요한 IOPS 수에 따라 Amazon Elastic VMware Service 데이터 저장소에 최소 처리량이 필요합니다.
** FSx for ONTAP 파일 시스템 구성에 따라 Amazon Elastic VMware Service 환경이 최적의 성능을 발휘하려면 최소한의 외부 데이터 저장소가 필요합니다.


====
. 준비가 되면 *다음*을 선택하여 마이그레이션 계획을 검토하세요.
. 계획을 검토합니다. 각 섹션을 확장하여 계획 세부 정보를 확인하세요.
. 선택적으로, 마이그레이션 계획에 만족하면 이를 템플릿이나 PDF로 저장할 수 있습니다.
+
** 마이그레이션 계획을 템플릿으로 저장하려면 *계획 내보내기*를 선택하세요.  `.json` 컴퓨터의 형식입니다. 나중에 계획을 가져와 요구 사항이 유사한 시스템을 배포할 때 템플릿으로 사용할 수 있습니다.
** 배포 계획을 다운로드하려면 *계획 다운로드*를 선택하세요.  `.pdf` 계획을 검토용으로 배포할 수 있는 형식입니다.


. link:deploy-fsx-file-system-evs.html["VMware 워크로드에 권장되는 FSx for ONTAP 파일 시스템을 구축하십시오"]..

