---
settings:
  name: VMware workloads
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  release_notes_autogen:
    release_notes_repo: workload-relnotes
  langs: ko-kr,us-en,de-de,es-es,fr-fr,it-it,pt-br,ja-jp,zh-cn,zh-tw
sidebar:
  entries:
  - title: VMware 워크로드 문서
    url: "/index.html"
  - title: 릴리스 정보
    entries:
    - title: 새로운 소식
      url: "/whats-new.html"
  - title: 시작하십시오
    entries:
    - title: VMware용 NetApp Workload Factory에 대해 알아보세요
      url: "/learn-about-vmware-workloads.html"
    - title: Amazon EVS로 마이그레이션하기 위한 빠른 시작
      url: "/quick-start-evs.html"
    - title: Amazon EC2로의 마이그레이션을 빠르게 시작합니다
      url: "/quick-start-native.html"
    - title: AWS 기반 VMware Cloud로 마이그레이션을 빠르게 시작할 수 있습니다
      url: "/quick-start.html"
    - title: VMware 계획 센터 탐색
      url: "/explore-planning-center.html"
  - title: VMware 계획 센터를 사용하세요
    entries:
    - title: VM 인벤토리 데이터 업로드
      url: "/upload-vm-inventory.html"
    - title: Amazon Elastic VMware Service로 마이그레이션
      entries:
      - title: 저축 알아보기
        url: "/calculate-evs-savings.html"
      - title: 수동으로 배포 계획 생성
        url: "/launch-migration-advisor-evs-manual.html"
      - title: 마이그레이션 관리자를 사용하여 배포 계획을 생성합니다
        url: "/launch-migration-advisor-evs.html"
      - title: 권장 FSx for ONTAP 파일 시스템을 배포합니다
        url: "/deploy-fsx-file-system-evs.html"
    - title: Amazon EC2로 마이그레이션합니다
      entries:
      - title: 마이그레이션 관리자를 사용하여 배포 계획을 생성합니다
        url: "/launch-onboarding-advisor-native.html"
      - title: 권장 FSx for ONTAP 파일 시스템을 배포합니다
        url: "/deploy-fsx-file-system-native.html"
    - title: AWS 기반 VMware Cloud로 마이그레이션하십시오
      entries:
      - title: 마이그레이션 관리자를 사용하여 배포 계획을 생성합니다
        url: "/launch-onboarding-advisor.html"
      - title: 권장 FSx for ONTAP 파일 시스템을 배포합니다
        url: "/deploy-fsx-file-system.html"
      - title: FSx for ONTAP을 AWS의 VMware Cloud에 연결합니다
        url: "/connect-sddc-to-fsx.html"
      - title: 데이터를 새로운 인프라로 마이그레이션합니다
        url: "/migrate-data.html"
  - title: 지식 및 지원
    entries:
    - title: 지원을 위해 등록하십시오
      url: "/support-registration.html"
    - title: 도움을 받으십시오
      url: "/get-help.html"
  - title: 법적 고지
    url: "/legal-notices.html"
product-family:
  name: NetApp Workload Factory
  repo: workload-family
