---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes' 
summary: 워크로드 팩토리의 VMware 마이그레이션 어드바이저 구성 요소의 새로운 기능에 대해 알아보십시오. 
---
= 새로운 기능
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
워크로드 팩토리의 VMware Cloud Migration Advisor 구성 요소에 대한 새로운 기능에 대해 알아보십시오.



== 2024년 12월 1일



=== Amazon EC2 마이그레이션 어드바이저 개선 사항

이번 릴리즈의 VMware용 BlueXP  워크로드 팩토리는 마이그레이션 조언자 환경에서 다음과 같은 여러 가지 향상된 기능을 제공합니다.

* * 데이터 수집 *: VMware용 BlueXP  워크로드 팩토리에서는 마이그레이션 관리자를 사용할 때 특정 기간 동안 데이터를 수집할 수 있습니다.
* * VM 선택 *: VMware용 BlueXP  워크로드 팩토리에서는 이제 마이그레이션 배포에 포함할 VM을 선택할 수 있습니다.
* * 빠른 경험과 고급 경험 * : 마이그레이션 관리자를 사용하면 RVtools를 사용하여 빠른 마이그레이션 경험을 선택하거나 마이그레이션 어드바이저 데이터 수집기를 사용하는 고급 환경을 선택할 수 있습니다.


https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["마이그레이션 관리자를 사용하여 Amazon EC2에 대한 배포 계획을 생성합니다"]



== 2024년 11월 3일



=== VMware Migration Advisor 데이터 축소율이 도움이 됩니다

이번 VMware용 Workload Factory 릴리즈에는 데이터 축소율 지원 기능이 있습니다. 데이터 축소율 도우미를 통해 AWS 클라우드 온보딩을 준비할 때 VMware 인벤토리 및 스토리지 공간에 가장 적합한 비율을 결정할 수 있습니다.

https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["마이그레이션 관리자를 사용하여 Amazon EC2에 대한 배포 계획을 생성합니다"]



== 2024년 9월 19일



=== VMware 마이그레이션 어드바이저의 향상된 기능

이번 VMware용 워크로드 팩토리에는 기능 및 안정성이 향상되었으며 VMware 마이그레이션 관리자를 사용할 때 마이그레이션 계획을 가져오고 내보내는 기능이 포함되어 있습니다.

https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["마이그레이션 관리자를 사용하여 Amazon EC2에 대한 배포 계획을 생성합니다"] == 2024년 9월 1일



=== Amazon EC2로 마이그레이션합니다

VMware용 워크로드 팩토리에서는 이제 VMware 마이그레이션 어드바이저를 사용하여 Amazon EC2로의 마이그레이션을 지원합니다.



== 2024년 7월 7일



=== VMware용 워크로드 팩토리 최초 릴리즈

초기 릴리즈에는 VMware 마이그레이션 어드바이저를 사용하여 온프레미스 vSphere 환경에서 현재 가상 머신 구성을 분석하고 권장 VM 레이아웃을 AWS 기반 VMware Cloud에 배포하고 맞춤형 Amazon FSx for NetApp ONTAP 파일 시스템을 외부 데이터 저장소로 사용할 계획을 생성하는 기능이 포함되어 있습니다.
