= FSx for ONTAP 파일 시스템 배포 마법사에서 Amazon Elastic VMware Service 기본 설정 소개
:allow-uri-read: 




=== FSx for ONTAP 파일 시스템 배포 마법사에서 Amazon Elastic VMware Service 기본 설정 소개

Amazon Elastic VMware Service의 외부 NFS 데이터 저장소로 사용할 FSx for ONTAP 파일 시스템을 배포하는 경우 이제 데이터 저장소가 연결될 EVS 환경을 선택할 수 있습니다.  이렇게 하면 배포 마법사의 여러 필드가 자동으로 채워져 배포 프로세스가 간소화됩니다.

https://docs.netapp.com/us-en/workload-vmware/deploy-fsx-file-system-evs.html["권장 FSx for ONTAP 파일 시스템을 배포합니다"]



=== VMware 워크로드에 대한 권한 변경

VMware 워크로드는 특정 작업에 필요한 권한에 대한 명확성을 제공하고 필요한 권한만 선택할 수 있는 세분성을 제공합니다.  자격 증명을 추가하면 이전 권한 모델인 _읽기 전용_ 및 _읽기/쓰기_ 대신 두 가지 권한 옵션 중에서 선택할 수 있습니다. 새로운 권한 모델은 권한 정책을 다음과 같이 구분합니다.

* _보기, 계획 및 분석_: EVS 가상화 환경 인벤토리를 보고, 시스템에 대한 잘 설계된 분석을 얻고, 절감 방안을 알아보세요.
* _데이터 저장소 배포 및 연결_: 권장되는 VM 레이아웃을 AWS vSphere 클러스터의 Amazon EVS, Amazon EC2 또는 VMware Cloud에 배포하고 사용자 정의된 Amazon FSx for NetApp ONTAP 파일 시스템을 외부 데이터 저장소로 사용합니다.


자격 증명을 추가할 때 VMware 워크로드에 제공하려는 액세스 수준에 따라 이러한 권한 정책 중 하나 이상을 선택할 수 있습니다.

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html["워크로드 팩토리 권한 참조"^]



=== Amazon EC2 마이그레이션 어드바이저 개선 사항

VMware용 NetApp Workload Factory의 이번 릴리스에서는 마이그레이션 어드바이저 환경에 대한 여러 가지 개선 사항이 적용되었습니다.

* *마이그레이션 계획 저장 또는 다운로드*: 이제 마이그레이션 계획을 PDF 또는 CSV 파일로 저장하거나 다운로드할 수 있습니다.  마이그레이션 계획을 저장하면 해당 계획이 Workload Factory 계정에 저장됩니다.

